#define PIN_MOTOR_STEP 17
#define PIN_MOTOR_DIRECTION 16
#define PIN_MOTOR_ENABLE 5

#define PIN_SENSOR_PAPER 34
#define PIN_SENSOR_HEAD 35

#define PIN_THERMISTOR_MOTOR 23
#define PIN_THERMISTOR_HEAD 22